name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt update
        apt install -y \
          sudo \
          cmake build-essential \
          libx11-dev \
          libssl-dev libplist-dev \
          libavahi-compat-libdnssd-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: Run cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: make -j$(nproc) -C build
